### ISSUE TITLE
[Feature] Design UX - Creating a week meal plan

### ISSUE THREAD

**Issue by sedward5** [sedward5/MealFrame#9]
### Feature Summary

Create a simple design doc for how users would create a weekly meal plan

### What problem does this feature solve?

Before development begins design how a user would input their meal plan for the week. How would the app help them. Make suggestions 

### Proposed Solution

This should hopefully be more than just a template for MD files. But shouldn’t exceed the capabilities of Hugo. 

### Scope

- [x] Hugo content structure
- [ ] Recipe import system
- [ ] GitHub Actions automation
- [x] Shortcodes or UI templates
- [ ] Data structure or storage

**Comment by sedward5** [comment]
```yaml
sunday:
  title: Nachos and Beans
  recipe_url: https://remote-site.com/nachos
  recipe_path: /recipes/black-beans

monday:
  title: Out to Eat

tuesday:
  title: Pizza and Salad
  ingredients:
    - cauliflower crust
    - marinara
    - mozzarella
  recipe_url: https://remote-site.com/salad
```
